name: Python CLI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Add any requirements here if needed, else skip.

    - name: Run tests
      run: |
        echo "Testing CLI by listing tasks"
        python task_cli.py list

    - name: Run linting
      run: |
        pip install flake8
        flake8 task_cli.py

